Add the XHarness bootstrap script
dotnet/xharness pull request #396
Opened 2020-12-09 15:39 UTC by premun

Adds a simple script that installs XHarness locally in a folder so that you can try XHarness out easily.

2020-12-09 16:03 UTC, mandel-macaque approved these changes

2020-12-09 16:09 UTC, akoeplinger requested changes

2020-12-09 16:09 UTC, akoeplinger commented on README.md
> +- Android scenarios are supported on Linux, macOS and Windows systems with Android emulators
not just emulators, also devices :)

2020-12-09 16:09 UTC, akoeplinger commented on README.md
> +It will also pull a sample iOS app for you and you can then try running the XHarness tool right away (instructions will be printed on screen):
I don't think we should do this in the bootstrap script. It's unrelated to xharness and will only work on macOS.

2020-12-09 16:09 UTC, akoeplinger commented on tools/xharness-bootstrap.sh
> +printf "Run XHarness using:\n\033[0;36m./xharness/xharness ios test -a=%s -o=o -t=ios-simulator-64\033[0m\n\n" "$app_name"
I think we can still print this usage instruction (maybe with --long-option's instead so it's clearer what they do) but we shouldn't download the sample .app

2020-12-09 17:06 UTC, greenEkatherine approved these changes

2020-12-10 11:51 UTC, premun commented
This is the output of the script:
![image](https://user-images.githubusercontent.com/7013027/101768875-76813380-3ae6-11eb-968e-8ee10357f99c.png)

2020-12-10 20:49 UTC, akoeplinger commented on README.md
> +It will also pull a sample iOS app for you and you can then try running the XHarness tool right away (instructions will be printed on screen):
This sentence is no longer true in the latest iteration :)

2020-12-10 20:49 UTC, akoeplinger approved these changes

2020-12-11 09:52 UTC, merged